import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/_components/layout/templates/header";
import ScrollDetector from "@/app/_components/layout/templates/scrollDetector";
import Main from "@/app/_components/layout/templates/main";

//uxo

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//基本レイアウトファイル。サーバーコンポーネントとして実装する。

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/*この階層でHeaderとMainを定義する。モバイルでのoverflowの制御もここで行う。このwrapperのrefが必要な場合は別コンポーネントとして切り分ける可能性もある。*/}
        <div className={'w-[100svw] h-[100svh] overflow-y-scroll bg-background-1'}>
          <ScrollDetector/>
          <Header/>
          <Main>{children}</Main>
        </div>
      </body>
    </html>
  );
}
